app_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    defaults:
            _format: json
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

