# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.battle_extension:
        class: AppBundle\Twig\BattleExtension
        tags:
            - { name: twig.extension }

    battle.battle_manager:
        class: AppBundle\Battle\BattleManager
        arguments: ['@doctrine.orm.entity_manager']

    battle.power_manager:
        class: AppBundle\Battle\PowerManager
        arguments: ['@doctrine.orm.entity_manager']
    api_problem_subscriber:
        class: AppBundle\EventListener\ApiEventListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments: ['@router']

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
        public: true

    admin.blog_post:
            class: AppBundle\Admin\BlogPostAdmin
            arguments: [~, AppBundle\Entity\BlogPost, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Blog post }
            public: true