version: '2'
services:
  testdb:
    environment:
      - MYSQL_ROOT_PASSWORD=challouf50
    image: "mysql:5.6"
    ports:
     - "3308:3306"

  api:
    image: 'phpmentors/symfony-app:php56'
    environment:
     - SYMFONY_ENV=test
    command: sh -c "chmod +x wait-for-it.sh && ./wait-for-it.sh testdb:3306 -t 30 && /usr/local/sbin/system-init"
    ports:
     - "8889:89"
    volumes:
     - ../:/var/app
     - ./wait-for-it.sh:/root/wait-for-it.sh
     - ./composer.phar:/var/app/composer.phar
    depends_on:
      - testdb
